<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>list</title> 

    <link rel="stylesheet" href= "/base/css/bootstrap.min.css">
    <link rel="stylesheet" href="/base/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="/base/css/divider-text-middle.css">
    <link rel="stylesheet" href="/base/css/btns.css">
    <link rel="stylesheet" href="/base/css/left-nav-style.css">
    <link rel="stylesheet" href="/base/css/styles.css">
    <script
        src="https://code.jquery.com/jquery-3.6.1.min.js" 
        crossorigin="anonymous">
    </script>
    <link rel="stylesheet" type="text/css" href="/base/css/datatables.min.css">

</head>

<body>
<?php echo $this->getContent(); ?>
<script
src="https://code.jquery.com/jquery-3.6.1.min.js"
integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ="
crossorigin="anonymous">
</script>
<script src="/base/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/base/js/datatables.min.js" ></script>
</body>

</html>
