  <link rel="stylesheet" href="/base/css/styleenter.css">

  <section class="container">
    <div class="login">
      <h1>Войти в личный кабинет</h1>
      <form method="post">
        <p><input type="text" name="login" value="" placeholder="Логин" style="width:360px"></p>
        <p><input type="password" name="password" value="" placeholder="Пароль" style="width:360px"></p>
        <p class="remember_me">
        </p>
        <p class="submit"><input type="submit" name="commit" value="Войти"></p>
      </form>
    </div>
  </section>
