
<script src="/base/js/adminhistory.js"></script>

<input type="checkbox" id="navmenu-toggle" hidden>
<nav class="navmenu">
    <label for="navmenu-toggle" class="navmenu-toggle" onclick></label>
    <ul>
        <li><a href="admingbr">Фонды и подразделения</a></li>
        <li ><a href="" style="pointer-events: none; color: #888;font-size: 18pt;">Статистика</a></li>
        <li ><a href="exitFromAccount">Выход</a></li>
    </ul>
</nav>

<div class="row">
    <div class="col">
        <div class="row bgstylecolor" style="height:100px" >
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xxl-12">
        <div class="row" style="height: 850px;margin-top:10px">
            <div class="col" style="width: 203px;"></div>
            <div class="col-xxl-10" style="display: flex;justify-content: center;">
                <div class="row " style="height: 765px; width:90%;" >
                    <div class="col" style="height:550px">
                        <table  id="startTable" class="table" >
                            <thead>
                                <tr>
                                    <th class ="tablecolumn">ФИО</th>
                                    <th class ="tablecolumn">Дивизион</th>
                                    <th class ="tablecolumn">Роль</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col"></div>
        </div>
    </div>
</div> 
<footer class="text-center bgstylecolor footer" >
    <div class="container text-white py-4 py-lg-5">
        <ul class="list-inline">
            <li class="list-inline-item me-4"><a class="link-light" href="#">Разработчики</a></li>
            <li class="list-inline-item me-4"><a class="link-light" href="#">Компания</a></li>
            <li class="list-inline-item"><a class="link-light" href="#">О программе</a></li>
        </ul>
        <p class="mb-0" >Copyright © 2023 </p>
    </div>
</footer>


